# Generated by Django 4.2.3 on 2023-07-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_celerycompletedtasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="celerycompletedtasks",
            name="success",
        ),
        migrations.AddField(
            model_name="celerycompletedtasks",
            name="status",
            field=models.CharField(
                choices=[("OK", "SUCCESS"), ("FAILED", "FAILED"), ("PROCESSING", "PROCESSING")], default="OK"
            ),
            preserve_default=False,
        ),
    ]
