# Generated by Django 4.2.3 on 2023-07-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_celerycompletedtasks_success_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="celerycompletedtasks",
            name="task_id",
            field=models.CharField(default="aspdoiaposdipoasidpoi", max_length=256),
            preserve_default=False,
        ),
    ]
